[versions]
agp = "8.11.1"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
kotlin = "2.2.0"
gobley = "0.3.7"
vanniktech-publish = "0.34.0"
groupId = "io.github.shadmanadman"
artifactId = "kchacha20"
snapshotVersion = "0.0.55-SNAPSHOT"
[libraries]



[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktechPublish = {id = "com.vanniktech.maven.publish", version.ref = "vanniktech-publish"}
gobleyCargo ={id = "dev.gobley.cargo", version.ref= "gobley"}
devGobleyUniffi ={id = "dev.gobley.uniffi", version.ref= "gobley"}
